sylius_resource:
    resources:
        webburza.article:
            classes:
                controller: Webburza\Sylius\ArticleBundle\Controller\ArticleController
                repository: Webburza\Sylius\ArticleBundle\Doctrine\ORM\ArticleRepository
                model: Webburza\Sylius\ArticleBundle\Entity\Article
                form:
                    default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleType
            translation:
                classes:
                    model: Webburza\Sylius\ArticleBundle\Entity\ArticleTranslation
                    form:
                        default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleTranslationType

        webburza.article_category:
            classes:
                controller: Webburza\Sylius\ArticleBundle\Controller\ArticleCategoryController
                repository: Webburza\Sylius\ArticleBundle\Doctrine\ORM\ArticleCategoryRepository
                model: Webburza\Sylius\ArticleBundle\Entity\ArticleCategory
                form:
                    default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleCategoryType
            translation:
                classes:
                    model: Webburza\Sylius\ArticleBundle\Entity\ArticleCategoryTranslation
                    form:
                        default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleCategoryTranslationType

        webburza.article_image:
            classes:
                model: Webburza\Sylius\ArticleBundle\Entity\ArticleImage

webburza_sylius_article:
    slug: articles
    file_browser:
        browse_url: ""
        upload_url: ""
