sylius_resource:
    resources:
        webburza.article:
            classes:
                controller: Webburza\Sylius\ArticleBundle\Controller\ArticleController
                repository: Webburza\Sylius\ArticleBundle\Doctrine\ORM\ArticleRepository
                model: Webburza\Sylius\ArticleBundle\Entity\Article
                form:
                    default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleType
            translation:
                classes:
                    model: Webburza\Sylius\ArticleBundle\Entity\ArticleTranslation
                    form:
                        default: Webburza\Sylius\ArticleBundle\Form\Type\ArticleTranslationType
